title: 'BitDevs CDMX'
tagline: 'BitDevs es una comunidad para aquellos interesados en discutir y participar en la investigación y desarrollo de Bitcoin y protocolos relacionados.'

menu:
  - {name: 'Acerca de BitDevs', url: '/about'}
  - {name: 'Eventos', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/bitdevs-cdmx/', external: true}
